[context.deploy-preview]
command = "bundle exec jekyll build"
publish = "_site/"
skip_processing = true

[context.branch-deploy]
command = "bundle exec jekyll build"
publish = "_site/"
skip_processing = true
